dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  encrypt: ^5.0.1

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  encrypt: ^5.0.1
  logging: ^1.0.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  audioplayers: ^5.2.1
  cached_network_image: ^3.3.1